environment:
  nodejs_version: "20"

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - docker build -t luciaansino/compraonline:latest .

test_script:
  - node --version
  - docker run -tv /app/test luciaansino/compraonline:latest

build: off
