environment:
  nodejs_version: "20"

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - docker run -tv %APPVEYOR_BUILD_FOLDER%:/app/test luciaansino/compraonline:latest
build: off
