environment:
  nodejs_version: "20"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g pnpm@latest

before_build:
  - docker build -t luciaansino/compraonline:latest .

test_script:
  - node --version
  - docker run -tv $(pwd):/app/test luciaansino/compraonline:latest

build: off
