environment:
  nodejs_version: "20"

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - docker build -t luciaansino/compraonline:latest .
  - docker run -tv /app/test luciaansino/compraonline:latest

build: off
