name: Node.js CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/-1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Docker Image
        run: docker build -t luciaansino/compraonline .

      - name: Run tests
        run: docker run -tv `pwd`:/app/test luciaansino/compraonline